gravitational/careers

careers.md
The link to your UX/Product Leader was incorrect.
Update to correct filename.
_P.S. I'm not really a designer, but good luck finding someone!_ ;-)
=> Fix broken link to product design leader career.

levels.tex
@klizhentas @russjones @r0mant @knisbet @alex-kovoy @wadells
=> Adding mentoring language to L1-3 

README.md, hn.md, jobs/backend.md, jobs/fullstack.md
The old gravitational ones 404.
=> Update lever links

challenges/platform/devops.md
Proposal to add L4/L5 interviews to the devops interview process.
=> add level 4 and 5 interview levels to devops challenge

challenges/platform/README.md, challenges/platform/devops.md, challenges/platform/troubleshooting.md
Update grammar in a few places.
=> Minor grammatical updates.

README.md, jobs/backend.md, jobs/fullstack.md, teams.md
- make the about us sections better match our careers page
- update job descriptions 
- update teams.md with latest projects and goals
=> Updates for Teleport Core - FY2023

challenges/frontend/challenge.md, challenges/systems/challenge.md, jobs/fullstack.md
Add some extra info to the challenges to be more explicit as to what we're expecting.
Note: A couple of these commits are formatting changes only. Best to review by commit to not get lost in the formatting noise.
=> Clarify challenges

teams.md
Also update web applications and link to the Teleport Connect blog
=> teams: add machine ID

challenges/frontend/challenge.md
This is based on feedback that we've given to some candidates in the past. During the interview process I wasn't sure myself how complex the app is supposed to be.
=> Expand scope creep section of "Pitfalls and Gotchas"

challenges/cloud/challenge.md, challenges/cloud/sre-server.go, challenges/cloud/sre.md
Initial pass of the SRE challenge documentation.
Still left outstanding is the creation of the GitHub repo that we'll use as a seed for this challenge.
Co-authored-by: Philippe M. Chiasson <gozer@goteleport.com>
Signed-off-by: Michael McAllister <michael.mcallister@goteleport.com>
=> Initial implementation of the SRE Challenge

challenges/cloud/sre.md
=> Fix SRE challenge link

challenges/frontend/challenge.md
Hopefully this will make it more clear that we need
just a very rudimentary filtering rather than a global
search.
=> Replace "searching" with "filtering"

challenges/security/application-security.md, challenges/security/cloud-security.md
While working on the cloud challenge I realized that limiting candidates
to a single PR is likely to create a confusing mega PR.  We'd prefer
smaller, more modular changes.
=> Clarify that multiple PRs may be expected

challenges/security/application-security.md, challenges/security/cloud-security.md
This was an implicit expectation, but we want to make our expectations explicit to candidates.
=> Add instructions for working with GitHub

challenges/fullstack/challenge.md, challenges/sre/challenge.md, challenges/systems/challenge-1.md, challenges/systems/challenge-2.md
- "Simple but robust" was confusing to candidates for the job worker authorization scheme. Rephrase to make it clear that simple is okay so long as it is secure and not easily bypassed.
- Replace references to "request" forwarders in the loab balancer challenge. Requests are typically an application layer concept and we're asking for a layer 4 implementation here.
=> Address some recent feedback

challenges/security/cloud-security.md
A candidate mentioned this expectation was not clear today.  We definitely don't want to have people scrambling to set up an account during the interview.
=> Add a note about needing an AWS account

teams.md
Updated teams page to include mission statements for Core and Cloud teams.
* [Rendered View](https://github.com/gravitational/careers/blob/rjones/update-teams-mission/teams.md)
=> Updated teams page

challenges/fullstack/challenge.md, challenges/sre/challenge.md, hn.md, jobs/backend.md, jobs/fullstack.md
This change aims to simplify the fullstack challenge by addressing some common areas of confusion and reducing scope.
Since we're currently only seeking L4 candidates, the requirements for other levels have been temporarily removed. We will make similar improvements when we have a need for more fullstack engineers at other levels.
Also clean up a few other details while we're here (countries that we hire in, terminology, etc)
=> Update fullstack challenge for FY24

challenges/sre/challenge.md
Update a bullet point we often clarify and get questions on.
=> sre challenge - update replica section

challenges/sre/challenge.md
This PR simplifies the SRE challenge, while adding additional Kubernetes programming focus for L5.
Changes:
- Removes Github Actions requirement
- Removes AWS/EKS requirement
- Simplifies HTTP or gRPC API
- Replaces state tracking with a watch request (L4+)
- Requires a CRD for reconciliation (L5)
=> Simplify and clarify SRE challenge

challenges/sre/challenge.md
Removes outdated references to scaffold in SRE challenge.
=> Fix SRE challenge intro

challenges/frontend/challenge.md, challenges/fullstack/challenge.md, hn.md, jobs/backend.md, jobs/fullstack.md, teams.md
- re-add fullstack challenge for L1-L2
- update Teleport messaging
- remove mentions of work location (it's easiest to just refer to the postings on our careers page which are more up to date with location and other requirements)
=> FY25 updates

teams.md
Adjust the cloud teams section of our teams document to match our current organizational structure.
=> Update cloud teams

teams.md
Adds a little more detail to the Cloud platform team description.
=> Enhance Cloud platform team description

challenges/support/challenge.md
Removed topics that are no longer covered and removed the "some of the hardest problems" paragraph since we've removed hosts 2 and 3.
=> Updated CRE challenge.

challenges/fullstack/challenge-policy.md
Add a new challenge for fullstack Policy role. The requirements are the same as our regular fullstack challenge, except the UI should show the directory structure as a graph, not a list. I also remove levels 1-3 as we're only looking for L4 now.
Note: Apart from removing the L1-L3 levels I only modified the **UI** and **Requirements** sections.
=> Add policy fullstack challenge

teams.md
Updates with more recent projects and focus on not only granting access to resources but securely issuing cryptographic identities to workloads.
=> Update Machine ID team Overview

challenges/cloud/README.md, challenges/cloud/sre.md, challenges/sre/challenge.md
No functional changes.  Mostly reorganizing information, being more specific on expectations for the workflow, etc.
=> SRE challenge refresh

challenges/README.md, challenges/security-automation/challenge.md
Updated Security and Automation challenge to allow Python for L4 submissions.
=> Updated Security and Automation challenge

challenges/systems/challenge-1.md
=> update challenge 1 text

challenges/support/challenge.md
Update support team challenge to remove CLI instructions as they have been confusing to use.
=> Update support challenge.

challenges/README.md, challenges/systems/challenge-2.md
Added second systems engineering challenge called OIDC CLI which tests secure coding by implementing an CLI tool that can perform OIDC authentication.
=> Added second systems engineering challenge.

challenges/ai-ml/challenge-1.md
=> update ai challenge

challenges/fullstack/challenge.md, challenges/product/challenge-1.md, challenges/security-automation/challenge.md, challenges/sre/challenge.md, challenges/systems-intern/challenge.md, challenges/systems/challenge-1-windows.md, challenges/systems/challenge-1.md, challenges/systems/challenge-2.md
Added the following "Use of AI" pitfall to all challenges.
"Use of AI. Don't outsource your thinking to an AI. We recommend using AI for use cases like learning about a new problem space, exploring APIs, and finding missing edge cases. However, we strongly recommend you write the design document and all code yourself."
=> Add "Use of AI" pitfall.

challenges/sre/challenge.md
Updated SRE challenge structure to match all other challenges. Content is unchanged.
=> Updated SRE challenge structure.
